#!/usr/bin/env python3
"""
Regenerate POOL.md — the taught-material snapshot handed to authoring agents.

RUN THIS IMMEDIATELY BEFORE LAUNCHING EVERY BATCH, not after wiring one.

A stale pool has caused one real sequencing bug (a2_time_past recycled weather
words while sitting before the weather unit) and made four agents needlessly
cautious — refusing to use wypilem, jem, isc, chodzic, bedzie because a pool
generated a few nodes earlier did not list them yet.

POSITION MATTERS. The pool for a unit is everything taught STRICTLY BEFORE it on
path_order — not everything taught anywhere. Units are authored out of order, so
live nodes routinely sit later on the path than the one being written. Without
--before, this script over-reports and an agent may use material that is not yet
legally available (caught by a2_ordering_func, which correctly refused to use
a2_dat_chunks material sitting one node later).

Usage:
    py -X utf8 sequencing/make_pool.py <output-path>
    py -X utf8 sequencing/make_pool.py <output-path> --before a2_ordering_func
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # .../rupl-exp (codex/sequencing/make_pool.py -> up 2)
DATA = ROOT / "data"


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    out = Path(sys.argv[1])
    before = None
    if "--before" in sys.argv:
        before = sys.argv[sys.argv.index("--before") + 1]

    tree = json.loads((DATA / "tree.json").read_text(encoding="utf-8"))
    by_id = {n["id"]: n for n in tree.get("nodes") or []}
    order = tree.get("path_order") or []

    cutoff = len(order)
    if before:
        if before not in order:
            print(f"ERROR: {before} is not on path_order")
            return 1
        cutoff = order.index(before)

    lemmas: list[str] = []
    structures: list[str] = []
    trail: list[str] = []
    for i, nid in enumerate(order):
        if i >= cutoff:
            break
        node = by_id.get(nid)
        if not node or node.get("status") != "live" or not node.get("content"):
            continue
        pack = json.loads((DATA / node["content"]).read_text(encoding="utf-8"))
        lemmas += pack.get("teaches_lemmas") or []
        structures += pack.get("teaches_structures") or []
        trail.append(nid)

    lemmas = sorted({str(x).lower() for x in lemmas})
    structures = sorted(set(structures))

    out.write_text(
        "\n".join(
            [
                f"# Taught pool — END OF {trail[-1]} ({len(trail)} live nodes)",
                "",
                "Everything here may be RECYCLED. Anything not here may not be used "
                "unless your own pack teaches it.",
                "",
                "Generated by codex/sequencing/make_pool.py — regenerate before "
                "every batch launch.",
                "",
                f"## Structures ({len(structures)})",
                ", ".join(f"`{s}`" for s in structures),
                "",
                f"## Lemmas ({len(lemmas)})",
                ", ".join(lemmas),
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"POOL -> {out}")
    print(f"  {trail[-1]} · {len(trail)} nodes · {len(lemmas)} lemmas · {len(structures)} structures")
    return 0


if __name__ == "__main__":
    sys.exit(main())
